export default function (nga, customers, categories, products, reviews, commands) {
    return nga.menu()
        .addChild(nga.menu(customers)
            .icon('<span class="fa fa-user fa-fw"></span>'))
        .addChild(nga.menu().title('Sales')
            .icon('<span class="fa fa-shopping-cart fa-fw"></span>')
            .active(path => path.indexOf('/commands') === 0)
            .addChild(nga.menu()
                .title('Orders')
                .link('/commands/list?search={"status":"ordered"}')
                .icon('<span class="fa fa-credit-card fa-fw"></span>'))
            .addChild(nga.menu()
                .title('Invoices')
                .link('/commands/list?search={"status":"delivered"}')
                .icon('<span class="fa fa-usd fa-fw"></span>'))
            .addChild(nga.menu()
                .title('Cancels')
                .link('/commands/list?search={"status":"cancelled"}')
                .icon('<span class="fa fa-hand-o-left fa-fw"></span>'))
        )
        .addChild(nga.menu().title('Catalog')
            .icon('<span class="fa fa-th-list fa-fw"></span>')
            .addChild(nga.menu(categories)
                .icon('<span class="fa fa-tags fa-fw"></span>'))
            .addChild(nga.menu(products)
                .icon('<span class="fa fa-picture-o fa-fw"></span>'))
        )
        .addChild(nga.menu(reviews)
            .icon('<span class="fa fa-comments fa-fw"></span>'))
    ;
}
